#    Copyright 2026 Genesis Corporation.
#
#    All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
from __future__ import annotations

import uuid as sys_uuid

import rich_click as click

from exordos import constants as c
from exordos.clients import base_client
from exordos.cmd.base import create_entity_group
from exordos.common.table import show_data

ENTITY = "access key"
ENTITY_COLLECTION = c.S3_ACCESS_KEY_COLLECTION
FIELDS_MAP = {
    "UUID": "uuid",
    "Project": "project_id",
    "User": "user",
    "Access key": "access_key",
    "Status": "status",
}


# The secret key is returned by the API on creation only, so there is nothing
# to update afterwards: a key is added and deleted.
keys_group = create_entity_group(
    ENTITY,
    ENTITY_COLLECTION,
    FIELDS_MAP,
    group_name="keys",
    parents=["instance", "user"],
)


@click.command("add", help=f"Add a new {ENTITY}")
@click.pass_context
@click.option(
    "-u",
    "--uuid",
    type=click.UUID,
    default=None,
    help=f"UUID of the {ENTITY}",
)
@click.option(
    "-p",
    "--project-id",
    type=click.UUID,
    required=True,
    help=f"UUID of the project in which to create the {ENTITY}",
)
@click.option(
    "-i",
    "--instance-uuid",
    type=str,
    required=True,
    help=f"UUID of the instance to create the {ENTITY} in",
)
@click.option(
    "--user-uuid",
    type=str,
    required=True,
    help=f"UUID of the user to create the {ENTITY} for",
)
@click.option(
    "--secret-key",
    type=str,
    default=None,
    help="Secret key, generated by the API when omitted",
)
def add_cmd(
    ctx: click.Context,
    uuid: sys_uuid.UUID | None,
    project_id: sys_uuid.UUID,
    instance_uuid: str,
    user_uuid: str,
    secret_key: str | None,
) -> None:
    client = base_client.get_user_api_client(ctx.obj.auth_data)
    if uuid is None:
        uuid = sys_uuid.uuid4()
    instance_url = f"{c.S3_INSTANCE_COLLECTION}{instance_uuid}"
    data = {
        "uuid": str(uuid),
        "project_id": str(project_id),
        "instance": instance_url,
        "user": f"{instance_url}/users/{user_uuid}",
    }
    if secret_key is not None:
        data["secret_key"] = secret_key

    entity = base_client.add_entity(
        client,
        ENTITY_COLLECTION.format(instance_uuid=instance_uuid, user_uuid=user_uuid),
        data,
    )
    # The secret key is shown here for the last time, it is hidden afterwards.
    show_data(entity)


keys_group.add_command(add_cmd, aliases=["a"])
